###
get http://localhost:3001/api/ads/634cb6f4fbfb527956bebc91

###
post http://localhost:3001/api/ads/634cb6f5fbfb527956bebc99 http/1.1
Content-Type: application/json

{
    "id": "11",
    "userId": 1,
    "img": "new IMG",
    "url": "new URL"
}

###
post http://localhost:3001/api/ads http/1.1
Content-Type: application/json

{
    "id": "11",
    "userId": 1,
    "img": "new IMG",
    "url": "new URL"
}

###
DELETE http://localhost:3001/api/ads/3 HTTP/1.1