###
get http://localhost:3001/api/ads/


###
post http://localhost:3001/api/ads/634cb6f5fbfb527956bebc99 http/1.1
Content-Type: application/json

{
    "id": "11",
    "userId": 1,
    "img": "new IMG",
    "url": "new URL"
}

###
post http://localhost:3001/api/ads http/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZwRV…FLEZ6mQ2TZzn_Y-Hkl8g6MVv-N_ss7u72t4UJBbDe8AV83pjw"
}

###
DELETE http://localhost:3001/api/ads/3 HTTP/1.1